# Generated by Django 4.1.7 on 2023-03-12 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRentalApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 12, 11, 17, 37, 872297, tzinfo=datetime.timezone.utc)),
        ),
    ]
