# Generated by Django 4.2.1 on 2023-05-29 19:33

import CarRentalApp.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarRentalApp', '0002_alter_customuser_city_alter_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', CarRentalApp.models.CustomUserManager()),
            ],
        ),
    ]
