# Generated by Django 4.2.1 on 2023-05-29 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarRentalApp', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
