# Generated by Django 4.2.2 on 2023-07-02 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRentalApp', '0004_remove_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Contact number must be exactly 11 digits.', regex='^\\d{11}$')])),
                ('message', models.TextField()),
            ],
        ),
    ]
